### ISSUE TITLE
recoilHelper called before nominal_weight definition in the mw analysis script

### ISSUE THREAD

**Issue by tyjyang** [WMass/WRemnants#129]
The recoilHelper called [here](https://github.com/WMass/WRemnants/blob/main/scripts/histmakers/mw_with_mu_eta_pt.py#L188) doesn't work as it uses nominal_weight before the column is defined in the script.

@jeyserma

**Comment by cippy** [comment]
Hi, this should be fixed in PR #123 which was merged not long ago. There might be other things to follow up elsewhere though.

**Comment by cippy** [comment]
I think this is fixed now, so I'll close it
