### ISSUE TITLE
Running data/mc comparison plots with procFilter option

### ISSUE THREAD

**Issue by sroychow** [WMass/WRemnants#89]
@dbruschi observed the following error while running the data mc stack plot script. He was running 
```python WRemnants/scripts/plotting/makeDataMCStackPlot.py mw_with_mu_eta_pt_nnpdf31.pkl.lz4 --hists pt eta unrolled --baseName nominal -p wplots/```

And got the error:- 
```
Traceback (most recent call last):
  File "/gpfs/ddn/cms/user/bruschin/Test/WRemnants/scripts/plotting/makeDataMCStackPlot.py", line 80, in <module>
    datasets = groups.getNames(args.procFilters)
  File "/gpfs/ddn/cms/user/bruschin/Test/WRemnants/wremnants/datasets/datagroups.py", line 145, in getNames
    return list(filter(lambda x: any([re.match(expr, x) for expr in matches]), self.groups.keys()))
  File "/gpfs/ddn/cms/user/bruschin/Test/WRemnants/wremnants/datasets/datagroups.py", line 145, in <lambda>
    return list(filter(lambda x: any([re.match(expr, x) for expr in matches]), self.groups.keys()))
TypeError: 'NoneType' object is not iterable
```

Looking at the [datagroups.py](https://github.com/WMass/WRemnants/blob/main/wremnants/datasets/datagroups.py#L143), 
The he issue is caused since ```matches``` is ```None``` type when ```procFilters``` is not used.  A fix to this is proposed below:-

```
    def getNames(self, matches=[], exclude=False):
        if not matches:
            return list(x for x in self.groups.keys())
        else:
            return list(filter(lambda x: any([re.match(expr, x) for expr in matches]), self.groups.keys()))
```
If ```matches``` is empty, all the procs will be returned, if not the filtered list(which is the intended action when using the procFilter option)

**Comment by sroychow** [comment]
@kdlong @cippy let me know if this is fine and I can make a PR.

**Comment by cippy** [comment]
Yes, this is fine, sorry for getting late to it

**Comment by cippy** [comment]
I think it was, I'll close the issue
